rules:
  - description: default
    postconditions:
      predicate_id: skos:closeMatch
      weight: -0.02

  - description: exact to exact
    preconditions:
      subject_match_field_one_of:
        - oio:hasExactSynonym
        - rdfs:label
        - skos:prefLabel
      object_match_field_one_of:
        - oio:hasExactSynonym
        - rdfs:label
        - skos:prefLabel
    postconditions:
      predicate_id: skos:exactMatch
      weight: 2.0

  - description: >-
     label to label; note this is additive with the exact to exact rule,
      so the score just represents an additional small boost
    preconditions:
      subject_match_field_one_of:
        - rdfs:label
      object_match_field_one_of:
        - rdfs:label
    postconditions:
      predicate_id: skos:exactMatch
      weight: 0.5

  - description: shared xref match
    preconditions:
      subject_match_field_one_of:
        - oio:hasDbXref
        - skos:exactMatch
      object_match_field_one_of:
        - oio:hasDbXref
        - skos:exactMatch
    postconditions:
      predicate_id: skos:exactMatch
      weight: 4.0

  - preconditions:
      subject_match_field_one_of:
        - oio:hasExactSynonym
        - rdfs:label
      object_match_field_one_of:
        - oio:hasBroadSynonym
    postconditions:
      predicate_id: skos:broadMatch
      weight: 2.0

  - preconditions:
      subject_match_field_one_of:
        - oio:hasExactSynonym
        - rdfs:label
      object_match_field_one_of:
        - oio:hasNarrowSynonym
    postconditions:
      predicate_id: skos:narrowMatch
      weight: 2.0

  - synonymizer:
      description: Remove parentheses bound info from the label.
      match: '\([^)]*\)'
      match_scope: "*"
      replacement: ""

  - synonymizer:
      description: Remove box brackets bound info from the label.
      match: '\[[^)]*\]'
      match_scope: "*"
      replacement: ""
      
  - synonymizer:
      description: Depluralize.
      match: 's$'
      match_scope: "*"
      qualifier: related
      replacement: ""
      
  - synonymizer:
      description: X ecosystem is often the same as X.
      match: ' ecosystem'
      match_scope: "*"
      qualifier: related
      replacement: ""

      
  - synonymizer:
      description: X biome is often the same as X.
      match: ' biome'
      match_scope: "*"
      qualifier: related
      replacement: ""
      
  - synonymizer:
      description: X area is often the same as X.
      match: ' area'
      match_scope: "*"
      qualifier: related
      replacement: ""

  - synonymizer:
      description: X zone is often the same as X.
      match: ' zone'
      match_scope: "*"
      qualifier: related
      replacement: ""
      
      
